theme: minima

# Configurations
title: Divya Tiwari
longtitle: Divya Tiwari - Senior Software Engineer looking for early-mid stage StartUp
email: reach@divyatiwari.me

social:
  github:         divyatiwari5
